spring:
  application:
    name: wandoor

  datasource:
    url: "jdbc:oracle:thin:@localhost:1521/WANDOOR_DB"
    username: WANDOOR
    password: root
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    open-in-view: false

  flyway:
    enabled: true
    default-schema: WANDOOR
    schemas: WANDOOR
    create-schemas: false
    locations: classpath:db/migration

  mail:
    host: smtp.gmail.com
    port: 587
    username: oktaviaq.a@gmail.com
    password: ywia odzr xmbk jbex
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  logging:
    level:
      org:
        springframework:
          security=DEBUG:

server:
<<<<<<< HEAD
  port: 8080
=======
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
>>>>>>> 7e1522fda944f3965aa4bbae49600366c2163b09
