spring:
  application:
    name: wandoor

  datasource:
    url: "jdbc:oracle:thin:@localhost:1521/WANDOOR_DB"
    username: ${DB_USERNAME:wandoor}
    password: ${DB_PASSWORD:root}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    open-in-view: false

  flyway:
    enabled: true
    default-schema: WANDOOR
    schemas: WANDOOR
    create-schemas: false
    locations: classpath:db/migration

  mail:
    host: smtp.gmail.com
    port: 587
    username: oktaviaq.a@gmail.com
    password: ywia odzr xmbk jbex
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:rediswandoor}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.data.redis.core.RedisTemplate: DEBUG
    io.lettuce.core.protocol: DEBUG

# secret & expiry JWT
app:
  jwt:
    secret: ${JWT_SECRET:MySuperSecretKeyForBankingApp}
    expiration-ms: 3600000

server:
  port: 8081
  address: 0.0.0.0
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
